# Generated by Django 3.2.18 on 2023-04-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='ak',
            field=models.TextField(blank=True, null=True),
        ),
    ]
