# Generated by Django 3.2.18 on 2023-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_ak'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='anubhav',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
