# Generated by Django 3.2.18 on 2023-04-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_anubhav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='anubhav',
            new_name='anubhav_gupta',
        ),
    ]
